# Generated by Django 5.0.6 on 2024-06-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='table_name',
            field=models.CharField(default='default_table_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='data_file_upload',
            field=models.FileField(upload_to='uploads/tables/'),
        ),
    ]
