# Generated by Django 5.0.6 on 2024-06-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadmodel_table_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='table_name',
            field=models.CharField(default='Default Table Name', max_length=100),
        ),
    ]
