# Generated by Django 5.0.6 on 2024-06-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_messagingmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagingmodel',
            old_name='recipient',
            new_name='sender_email',
        ),
        migrations.RenameField(
            model_name='messagingmodel',
            old_name='sender',
            new_name='sender_username',
        ),
    ]
